apiVersion: v1
kind: Secret
metadata:
  name: backend-ontap
type: Opaque
stringData:
  username: vsadmin
  password: Netapp1!
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-ontap-nas-east
spec:
  version: 1
  backendName: nas-east
  storageDriverName: ontap-nas
  managementLIF: 192.168.0.133
  storagePrefix: east_
  credentials:
    name: backend-ontap
  supportedTopologies:
    - topology.kubernetes.io/region: east
    - topology.kubernetes.io/zone: east1