apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-ontap-nas-west
spec:
  version: 1
  backendName: nas-west
  storageDriverName: ontap-nas
  managementLIF: 192.168.0.133
  storagePrefix: west_
  credentials:
    name: backend-ontap
  supportedTopologies:
    - topology.kubernetes.io/region: west
    - topology.kubernetes.io/zone: west1