kind: Pod
apiVersion: v1
metadata:
  name: busybox-west
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
             - west1
  volumes:
    - name: nfsstorage
      persistentVolumeClaim:
       claimName: pvc-west
  containers:
    - name: busybox
      image: quay.io/trident-mirror/kcduk/busybox:1.31.1
      command:
        - /bin/sh
        - "-c"
        - "sleep 60m"
      volumeMounts:
        - mountPath: "/data"
          name: nfsstorage
