apiVersion: v1
kind: Secret
metadata:
  name: ontap-cluster-secret-username
type: Opaque
stringData:
  username: admin
  password: Netapp1!
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-ontap-nas-limit-volsize
spec:
  version: 1
  backendName: nas-limit-volsize
  storageDriverName: ontap-nas
  managementLIF: 192.168.0.133
  limitVolumeSize: 5g
  credentials:
    name: ontap-cluster-secret-username