apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: mydata-snapshot
  labels:
    app.kubernetes.io/name: kompaktlivelab-scenario03
    app: busybox
spec:
  volumeSnapshotClassName: csi-snapclass
  source:
    persistentVolumeClaimName: mydata