kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mydata-from-snap
  labels:
    app.kubernetes.io/name: kompaktlivelab-scenario03
    app: busybox
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: sc-nas-svm1
  dataSource:
    name: mydata-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io